-- Create a physician table with the following columns.
-- PhysicianID,
-- FirstName ,
-- LastName,
-- Title,
-- SSN
CREATE TABLE IF NOT EXISTS Public."physician" (
    "PhysicianID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    "Firstname" CHARACTER VARYING COLLATE pg_catalog."default",
    "Lastname" CHARACTER VARYING COLLATE pg_catalog."default",
    -- TODO: // add encryption
    "SSN" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT physician_pkey PRIMARY KEY ("PhysicianID")
)