-- Create an “appointment” table with the following columns.
-- AppointmentID,
-- PatientRecordNumber,
-- NurseID,
-- PhysicianID,
-- StartDateTime,
-- EndDateTime
-- ExamRoomID
CREATE TABLE IF NOT EXISTS Public."appointment" (
    "AppointmentID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    "PatientRecordNumber" bigint NOT NULL,
    "NurseID" BIGINT NOT NULL,
    "PhysicianID" BIGINT NOT NULL,
    "StartDateTime" TIMESTAMPTZ NOT NULL,
    "EndDateTime" TIMESTAMPTZ NOT NULL,
    "RoomID" INT,
    CONSTRAINT appointment_pkey PRIMARY KEY ("AppointmentID")
)