-- Create an “Room” table with the following columns.
-- RoomID,
-- RoomType,
-- Available
CREATE TYPE _RoomType AS ENUM(
    'surgery',
    'ICU',
    'maternity',
    'mental_health',
    'office'
);
CREATE TABLE IF NOT EXISTS Public."room" (
    "RoomID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    "RoomType" _RoomType NOT NULL,
    "Available" BOOLEAN NOT NULL DEFAULT TRUE,
    "RoomPhoneNumber" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT room_pkey PRIMARY KEY ("RoomID")
)