-- Create a “prescription” table with the following columns.
-- Make sure to implement to correct table relation between prescription,
-- patient and physician tables (this means adding the appropriate constraints)
-- PhysicianID,
-- PatientRecordNumber
-- MedicationID,
-- PrescribedOn,
-- AppointmentID,
-- Dosage
CREATE TABLE IF NOT EXISTS Public."prescription" (
    "PrescriptionID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    "PhysicianID" BIGINT NOT NULL,
    "PatientRecordNumber" BIGINT NOT NULL,
    "MedicationID" BIGINT NOT NULL,
    "PrescribedOn" TIMESTAMPTZ NOT NULL,
    "AppointmentID" BIGINT NOT NULL,
    "Dosage" SMALLINT NOT NULL,
    CONSTRAINT prescription_pkey PRIMARY KEY ("PrescriptionID")
)