-- creating a hospital table with hospital information
CREATE TABLE IF NOT EXISTS Public."hospital" (
    "HospitalID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    "FullName" CHARACTER VARYING COLLATE pg_catalog."default",
    "StreetNumber" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    "StreetName" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    "City" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    "State" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    "ZipCode" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    -- TODO: // add encryption
    "HospitalPhoneNumber" CHARACTER VARYING COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT hopistal_pkey PRIMARY KEY ("HospitalID")
)